server:
  port: 17000

system:
  windowSize: 5s
  mqtt:
    broker: "broker.hivemq.com"
    port: 1883
    username: "service"
    password: "master"
    clientId: "service-v1"

testPlanDir: "/Users/stefantobiasiewicz/Documents/Programing/Java/magisterka/System/Testplans/TestHuge"

spring:
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://192.168.31.111:5432/iot_system
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    dbcp2:
      default-schema: prod
  sql:
    init:
      platform: postgres
